# Generated by Django 3.2.6 on 2021-08-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210825_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='cat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.cat'),
            preserve_default=False,
        ),
    ]
