# Generated by Django 3.1 on 2020-08-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=51),
        ),
    ]
